"""Agent 2: Software Developer.

Drafts functional Python code modules implementing the approved PRD scope.
Generates a structured file tree of raw source files.
"""

import datetime
import logging
import os
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional
from google import genai
from google.genai import types
from pydantic import BaseModel, Field

# Ensure backend root is on sys.path for direct script execution
_backend_dir = str(Path(__file__).resolve().parent.parent.parent)
if _backend_dir not in sys.path:
    sys.path.insert(0, _backend_dir)

from app.graph.state import AgentState
from app.core.config import settings

logger = logging.getLogger(__name__)

# Client picks up environment variable GEMINI_API_KEY automatically
try:
    client = genai.Client()
except Exception:
    client = None


class GeneratedFile(BaseModel):
    path: str = Field(
        description="Relative file path, e.g., 'app/models/user.py' or 'app/services/auth.py'."
    )
    content: str = Field(
        description="Complete, executable Python code for the module."
    )


class DeveloperCodeOutput(BaseModel):
    summary: str = Field(
        description="Brief technical overview of the generated codebase architecture."
    )
    files: list[GeneratedFile] = Field(
        description="List of Python modules and configuration files generated dynamically from the PRD."
    )


def generate_python_scaffold(prd_text: str, ceo_critique: Optional[Dict[str, Any]] = None) -> Dict[str, str]:
    """Generates initial Python code modules based on the specification."""
    main_py = '''"""Main application entry point generated by TARA Developer Agent."""

import logging
import sys
from typing import Any, Dict

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s"
)
logger = logging.getLogger("tara_generated_app")

def process_request(payload: Dict[str, Any]) -> Dict[str, Any]:
    """Processes incoming data according to specification."""
    logger.info("Processing request with keys: %s", list(payload.keys()))
    if not payload:
        return {"status": "error", "message": "Empty payload received"}
    
    # Core domain business logic
    result = {
        "status": "success",
        "processed_items": len(payload),
        "data": payload
    }
    return result

def main() -> None:
    logger.info("Starting application service...")
    sample_data = {"service": "TARA Core", "version": "1.0.0"}
    res = process_request(sample_data)
    logger.info("Run result: %s", res)

if __name__ == "__main__":
    main()
'''

    models_py = '''"""Data models generated by TARA Developer Agent."""

from dataclasses import dataclass, field
from typing import Dict, Any, Optional
import datetime

@dataclass
class ServicePayload:
    service_name: str
    version: str
    metadata: Dict[str, Any] = field(default_factory=dict)
    created_at: str = field(default_factory=lambda: datetime.datetime.utcnow().isoformat())

    def to_dict(self) -> Dict[str, Any]:
        return {
            "service_name": self.service_name,
            "version": self.version,
            "metadata": self.metadata,
            "created_at": self.created_at,
        }
'''

    utils_py = '''"""Utility functions generated by TARA Developer Agent."""

import json
from typing import Any, Dict, Optional

def safe_json_loads(raw: str) -> Optional[Dict[str, Any]]:
    """Safely deserializes JSON string with error handling."""
    try:
        return json.loads(raw)
    except (ValueError, TypeError):
        return None

def format_timestamp(dt) -> str:
    """Formats datetime to standard ISO 8601 string."""
    return dt.isoformat()
'''

    return {
        "main.py": main_py,
        "models.py": models_py,
        "utils.py": utils_py,
    }


def developer_node(state: AgentState) -> Dict[str, Any]:
    """Executes Developer Agent drafting."""
    prd_text = state.get("prd_text", "")
    ceo_critique = state.get("ceo_critique", {})
    
    files = generate_python_scaffold(prd_text, ceo_critique)
    
    timestamp = datetime.datetime.utcnow().isoformat()
    log_entry = {
        "agent": "Developer",
        "stage": "code_generation",
        "message": f"Drafted {len(files)} Python modules: {', '.join(files.keys())}",
        "timestamp": timestamp,
    }
    
    return {
        "dev_code_files": files,
        "current_stage": "dev_completed",
        "logs": [log_entry],
    }
