"""Agent 2: Software Developer.

Drafts functional Python code modules implementing the approved PRD scope.
Generates a structured file tree of raw source files.
"""

import datetime
import logging
import os
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional
from google import genai
from google.genai import types
from pydantic import BaseModel, Field

# Ensure backend root is on sys.path for direct script execution
_backend_dir = str(Path(__file__).resolve().parent.parent.parent)
if _backend_dir not in sys.path:
    sys.path.insert(0, _backend_dir)

from app.graph.state import AgentState
from app.core.config import settings

logger = logging.getLogger(__name__)

# Client picks up environment variable GEMINI_API_KEY automatically
try:
    client = genai.Client()
except Exception:
    client = None


class GeneratedFile(BaseModel):
    path: str = Field(
        description="Relative file path, e.g., 'app/models/user.py' or 'app/services/auth.py'."
    )
    content: str = Field(
        description="Complete, executable Python code for the module."
    )


class DeveloperCodeOutput(BaseModel):
    summary: str = Field(
        description="Brief technical overview of the generated codebase architecture."
    )
    files: list[GeneratedFile] = Field(
        description="List of Python modules and configuration files generated dynamically from the PRD."
    )


def generate_code_from_prd(prd_content: str, human_notes: str = "") -> DeveloperCodeOutput:
    """Parses a PRD and generates real, dynamic Python modules matching the specification."""
    global client
    if client is None and os.getenv("GEMINI_API_KEY"):
        try:
            client = genai.Client()
        except Exception:
            client = None

    if client is not None:
        try:
            system_instruction = (
                "You are an expert Senior Software Engineer. Your task is to analyze a Product Requirement Document (PRD) "
                "and generate clean, modular, production-ready Python code.\n\n"
                "Guidelines:\n"
                "1. Dynamically structure the project files appropriate to the feature requirements (e.g., app/main.py, app/schemas.py, app/database.py).\n"
                "2. Do NOT use dummy placeholder code or generic hardcoded templates. Write full, functional Python implementations.\n"
                "3. Include proper type hints, docstrings, imports, and error handling in every generated module."
            )

            prompt = (
                f"Generate a full Python implementation based on this PRD:\n\n{prd_content}\n"
            )
            if human_notes:
                prompt += f"\nAdditional Requirements/Notes: {human_notes}"

            config = types.GenerateContentConfig(
                system_instruction=system_instruction,
                response_mime_type="application/json",
                response_schema=DeveloperCodeOutput,
                temperature=0.2,
            )

            # Use gemini-2.5-pro for complex coding, multi-file architecture, and reasoning
            response = client.models.generate_content(
                model="gemini-2.5-pro",
                contents=prompt,
                config=config,
            )

            if response.parsed and isinstance(response.parsed, DeveloperCodeOutput):
                return response.parsed
            if response.text:
                return DeveloperCodeOutput.model_validate_json(response.text)
        except Exception as exc:
            print("\n" + "="*50)
            print(f"❌ GEMINI API ERROR IN DEVELOPER AGENT: {exc}")
            print("="*50 + "\n")
            logger.warning("Gemini developer code generation error: %s", exc)

    return generate_code_fallback(prd_content)


def generate_code_fallback(prd_text: str = "") -> DeveloperCodeOutput:
    """Deterministic fallback code generator when LLM API keys are not supplied or network fails."""
    scaffold = generate_python_scaffold(prd_text)
    return DeveloperCodeOutput(
        summary="Modular Python scaffold with service models, entry point, and utilities.",
        files=[GeneratedFile(path=path, content=content) for path, content in scaffold.items()]
    )


def generate_python_scaffold(prd_text: str = "", ceo_critique: Optional[Dict[str, Any]] = None) -> Dict[str, str]:
    """Generates initial Python code modules based on the specification."""
    main_py = '''"""Main application entry point generated by TARA Developer Agent."""

import logging
import sys
from typing import Any, Dict

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s"
)
logger = logging.getLogger("tara_generated_app")

def process_request(payload: Dict[str, Any]) -> Dict[str, Any]:
    """Processes incoming data according to specification."""
    logger.info("Processing request with keys: %s", list(payload.keys()))
    if not payload:
        return {"status": "error", "message": "Empty payload received"}
    
    # Core domain business logic
    result = {
        "status": "success",
        "processed_items": len(payload),
        "data": payload
    }
    return result

def main() -> None:
    logger.info("Starting application service...")
    sample_data = {"service": "TARA Core", "version": "1.0.0"}
    res = process_request(sample_data)
    logger.info("Run result: %s", res)

if __name__ == "__main__":
    main()
'''

    models_py = '''"""Data models generated by TARA Developer Agent."""

from dataclasses import dataclass, field
from typing import Dict, Any, Optional
import datetime

@dataclass
class ServicePayload:
    service_name: str
    version: str
    metadata: Dict[str, Any] = field(default_factory=dict)
    created_at: str = field(default_factory=lambda: datetime.datetime.utcnow().isoformat())

    def to_dict(self) -> Dict[str, Any]:
        return {
            "service_name": self.service_name,
            "version": self.version,
            "metadata": self.metadata,
            "created_at": self.created_at,
        }
'''

    utils_py = '''"""Utility functions generated by TARA Developer Agent."""

import json
from typing import Any, Dict, Optional

def safe_json_loads(raw: str) -> Optional[Dict[str, Any]]:
    """Safely deserializes JSON string with error handling."""
    try:
        return json.loads(raw)
    except (ValueError, TypeError):
        return None

def format_timestamp(dt) -> str:
    """Formats datetime to standard ISO 8601 string."""
    return dt.isoformat()
'''

    return {
        "main.py": main_py,
        "models.py": models_py,
        "utils.py": utils_py,
    }


def developer_node(state: AgentState) -> Dict[str, Any]:
    """Developer Node executing dynamic code generation."""
    prd_text = state.get("prd_text", "")
    notes = state.get("human_feedback_notes", [])
    notes_str = "\n".join(notes) if notes else ""

    try:
        code_output: DeveloperCodeOutput = generate_code_from_prd(prd_text, notes_str)
        # Convert list of GeneratedFile objects into a key-value mapping
        generated_files = {f.path: f.content for f in code_output.files}
        summary = code_output.summary
    except Exception as exc:
        logger.warning("Gemini code generation failed, falling back: %s", exc)
        # Fallback dictionary if LLM fails
        generated_files = {
            "main.py": "# Fallback main entrypoint\nprint('Execution complete.')",
        }
        summary = "Generated using local fallback due to API error."

    # Ensure main.py entry point exists for downstream stages & test validation
    if "main.py" not in generated_files:
        main_entry = next((content for path, content in generated_files.items() if path.endswith("main.py")), None)
        if main_entry:
            generated_files["main.py"] = main_entry
        else:
            generated_files["main.py"] = generate_python_scaffold(prd_text).get("main.py", "# Main\n")

    log_entry = {
        "agent": "Developer",
        "stage": "code_generation",
        "message": f"Generated {len(generated_files)} dynamic Python modules: {list(generated_files.keys())}",
    }

    return {
        "dev_code_files": generated_files,
        "generated_code": generated_files,
        "code_summary": summary,
        "current_stage": "code_generated",
        "logs": [log_entry],
    }


if __name__ == "__main__":
    sample_prd = """
    # PRD: User Auth & Database Service
    - Fastapi endpoints for /register and /login
    - SQLite database connection using SQLAlchemy
    - Password hashing using passlib
    """

    result = generate_code_from_prd(sample_prd)
    print(f"Summary: {result.summary}\n")
    for file in result.files:
        print(f"--- File: {file.path} ---")
        print(file.content[:150])  # Print first 150 chars of each module
        print("\n")
